# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e9958805a0bb9bb41981e18ec568c1d449abfa20f5fc3ffbd3edcab81b0bca466abf7c7c2f9b8634add9f7ee4181277c53f95532299fe19f9812ab1c3666575

test:
  secret_key_base: 62c0362dda1178e1b55a5babe6cca23c359ccd2f4aa12cb759a42a915a5c85f8b591e269967224bb9c9a4939d87fbf0c32d6342e6e2363b35e204f3a30745af4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
